{
 "title": "Jenkins Monitoring",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "System Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jenkins health (Master)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_health_check_score{instance=~\".+\"}"
    }
   ]
  },
  {
   "title": "CPU Usage (Main)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_cpu_load{instance=~\".+\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (Main)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_memory_total_used{}" }
   ]
  },
  {
   "title": "JVM Heap Usage (Main)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{area=\"heap\"}) / jvm_memory_bytes_max{area=\"heap\"} * 100"
    }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jenkins_node_offline_value{})"
    }
   ]
  },
  { "title": "Job Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(jenkins_job_count_value{})  "
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_queue_size_value{})"
    }
   ]
  },
  {
   "title": "Sucessful Jobs (last 24hrs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(jenkins_runs_success_total{}[24h])))"
    }
   ]
  },
  {
   "title": "Failed Jobs (last 24hrs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(jenkins_runs_failure_total{}[24h])))"
    }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jenkins_executor_free_value{})"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jenkins_executor_in_use_value{})"
    }
   ]
  },
  {
   "title": "Aborted Jobs (last 24hrs)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(floor(increase(jenkins_runs_aborted_total{}[24h])))"
    }
   ]
  },
  {
   "title": "Unstable Jobs (last 24hrs)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(floor(increase(jenkins_runs_unstable_total{}[24h])))"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration{quantile=\"0.999\"}"
    }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jenkins_runs_success_total{})"
    }
   ]
  },
  { "title": "Alarm Metric View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Jenkins nodes offline",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_node_offline_value{instance=~\".+\"}"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_queue_size_value{instance=~\".+\"}"
    }
   ]
  }
 ]
}